### ISSUE TITLE
Указать Python 3 - only

### ISSUE THREAD

**Issue by TiberiumPY** [bureaucratic-labs/natasha#1]
Библиотека не работает на Python 2, поэтому стоит указать Python 3 - only.
Не работает из-за yargy

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "natasha\__init__.py", line 4, in <module>
    from yargy import FactParser, Combinator
  File "C:\python27\lib\site-packages\yargy\__init__.py", line 2, in <module>
    from yargy.parser import FactParser
  File "C:\python27\lib\site-packages\yargy\parser.py", line 3, in <module>
    from yargy.labels import LABELS_LOOKUP_MAP
  File "C:\python27\lib\site-packages\yargy\labels.py", line 70
    *case_token_genders, case_token_msf, case_token_gndr = next(results)
    ^
SyntaxError: invalid syntax

**Comment by dveselov** [comment]
Да, тут всё python3-only.

**Comment by dveselov** [comment]
Если у кого-нибудь будет желание портировать на вторую версию - буду рад (:

**Comment by TiberiumPY** [comment]
Я попробую портировать, там вроде бы не должно быть так сложно

**Comment by TiberiumPY** [comment]
Я всё портировал, осталось ЭТО:
((_, _, (start_position, _), *_), *_, (_, _, (_, end_position), *_)) = stack

**Comment by TiberiumPY** [comment]
pipeline.py, функция create_new_token...в yargy

**Comment by TiberiumPY** [comment]
Пожалуй, не буду пока переводить на Python 2:)

**Comment by dveselov** [comment]
Это - [PEP 3132: Extended Iterable Unpacking](https://www.python.org/dev/peps/pep-3132/) (:
Если проще, берется первый и последний токен, из них выдёргивается начальная позиция в тексте и конечная позиция.
Код для второй ветки будет выглядеть как-то так:
```python
head, tail = stack[0], stack[-1]
start_position = head[2][0]
end_position = tail[2][1]
```

**Comment by TiberiumPY** [comment]
Я знаю, что это за PEP.
просто мне кажется, этот код не очень красивый :) - "((, _, (start_position, _), *), *, (, , (, end_position), *_)) = stack"
Дело в том, что если библиотека была бы с поддержкой Python 2, она бы могла использовать всю мощь PyPy. PyPy3 медленнее намного
