### ISSUE TITLE
setup.py зацикленный импорт

### ISSUE THREAD

**Issue by TiberiumPY** [bureaucratic-labs/natasha#13]
setup.py должен устанавливать natasha со всеми зависимостями, но это не удастся, если yargy не установлен, т.к. в setup.py импортируется from natasha.commands import BuildDictionariesCommand
И поэтому импортируется `__init__.py`, в котором есть импорт yargy, поэтому возникает ошибка и установка не проходит

**Comment by dveselov** [comment]
Привет! Если ставить с PyPI - проблем нет.
Если ставить из master-бранча, то сначала нужно установить `yargy`.

**Comment by TiberiumPY** [comment]
@dveselov вот про это я и говорю - в setup.py нужно либо убрать импорт natasha, либо в setup.py сначала устанавливать yargy.
Все пакеты, которые я устанавливаю через setup.py из git clone ставятся без проблем :)

**Comment by dveselov** [comment]
Привет. Должно быть пофикшено в ff8800e04a09a901553fa0b934894ff299382075

**Comment by TiberiumPY** [comment]
@dveselov да, всё работает
