### ISSUE TITLE
error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by 31H0B1eV** [bureaucratic-labs/natasha#20]
При попытке добавить пользовательский словарь на ubuntu 16.04 ругается на то, что нужно установить Path. После того, как получает `Path = 'prsn.dawg'`, получаю ошибку о том, что файл не существует и после создания файла соответственно:
```
error: unpack requires a bytes object of length 4
```
Интересно было бы понять, что ожидается в Path.

**Comment by dveselov** [comment]
Привет!
В `Path` указывается путь до скомпилированного словаря DAWG, можно почитать об этом в документации: http://natasha.readthedocs.io/ru/latest/gazetteer/#id3
`Path` можно не указывать, если используется CPython и установлена библиотека [DAWG](https://pypi.python.org/pypi/DAWG/0.7.8) (`pip install dawg`)

**Comment by 31H0B1eV** [comment]
@dveselov спасибо за ответ. Т.е. сначала нужно скомпилировать словарь DAWG. документацию я видел, просто пытался передать множество слов в Dictionary и там же указывал Path. DAWG установленная но я запускаю код в jupyter из под virtualenv, не уверен можно ли там CPython подключить. Наверно проще с DWAG разобраться.
