### ISSUE TITLE
Разница в README и requirements.txt

### ISSUE THREAD

**Issue by TiberiumPY** [bureaucratic-labs/natasha#3]
README говорит, что natasha работает с Python 3.5+, однако зачем-то был добавлен enum34 в requirements.txt, который нужен для Python < 3.5

**Comment by dveselov** [comment]
Привет.
Я собираюсь добавить поддержку python 2.x и pypy в следующей версии, для этого и нужен enum34.

**Comment by TiberiumPY** [comment]
О, отлично!
PyPy3 уже может работать, ну всё равно круто

**Comment by TiberiumPY** [comment]
YAYAYAYA
